### ISSUE TITLE
Allow sertting of TCPDF congiguration constants

### ISSUE THREAD

**Issue by jbazant** [jonasarts/tcpdf-bundle#1]
Please add mechanism that allows setting TCPDF constants by application. At current state I am unable to set e.g. K_TCPDF_THROW_EXCEPTION_ERROR, which causes TCPDF to call die() on error as long as it is set to false (default).

**Comment by jonasarts** [comment]
The config currently resides at lib/config/tcpdf_config.php, there is also 

```
define('K_TCPDF_THROW_EXCEPTION_ERROR', false);
```

set.

Also have a look at lib/tcpdf_autoconfig.php about how and which constants are auto-loaded by TCPDF.

It is probably a nice idea to use Symfonys ConfigurationInterface to pass some constants to TCPDF. In combination with `define(K_TCPDF_EXTERNAL_CONFIG, true)`.

**Comment by jbazant** [comment]
Ye, I was missing the `K_TCPDF_EXTERNAL_CONFIG` constant. I think ticket can be closed now. But I still believe that `K_TCPDF_THROW_EXCEPTION_ERROR` should be set to `TRUE` by default.

Thank You
