### ISSUE TITLE
deprecation

### ISSUE THREAD

**Issue by lxregistry** [jonasarts/tcpdf-bundle#10]
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "jonasarts\Bundle\TCPDFBundle\DependencyInjection\TCPDFExtension".

**Comment by jonasarts** [comment]
Will look into it and upgrade to use future class.

**Comment by jonasarts** [comment]
Resolved
