### ISSUE TITLE
update for latest symfony

### ISSUE THREAD

**Issue by lxregistry** [jonasarts/tcpdf-bundle#2]
could you update it for latest symfony 4.1 and tcpdf 6.2.17?
also some non ASCII codes not show properly

also if I use
class PdfController extends AbstractController
is not working

it work only with
class PdfController extends Controller

**Comment by jonasarts** [comment]
checkout the latest version 4.x, if you're still on 1.x branch. 4.x works fine with symfony 4.0 and 4.1.
i just updated the docs for some symfony 4.x instructions.

there is no AbstractController in this bundle, you probably want to ask this on an other repository?
