### ISSUE TITLE
using TCPDF as external dependency

### ISSUE THREAD

**Issue by Rikijs** [jonasarts/tcpdf-bundle#3]
Hello!

Could you consider using TCPDF library as external dependency?

In my project I am using also FPDI that uses TCPDF as external dependency.
In my opinion it is 'cleaner' as it requires TCPDF package only once.

Sadly, at the moment, your bundle includes TCPDF as internal dependency.
So it results in 2 TCPDF instances in my project.
It creates problems...

Thank you.

**Comment by jonasarts** [comment]
Updated v4.0.2 using tecnickcom/TCPDF via composer / autoload.
Seems to work fine.
This also makes this bundle kind of obsolete, as you can simply inject tecnickcom/TCPDF.

**Comment by Rikijs** [comment]
@jonasarts 
Thank you for speedy changes.
Updated - and it works.
