### ISSUE TITLE
Notice: Undefined property: jonasarts\Bundle\TCPDFBundle\TCPDF\TCPDF::$pdfa_mode

### ISSUE THREAD

**Issue by cube4d** [jonasarts/tcpdf-bundle#6]
Hi,

if i run my code and send it directly to the browser everything is fine and i get my PDF like it should be, but
if i change it to "F" and want to save it as a file, i get this error... but my PDF is saved correctly.

The problem is that my code has a for loop and it should generate a few PDFs, but it stall then with this Error.

Thanks for your help :-)

**Comment by jonasarts** [comment]
Please add your code and tell what you want to achieve, that we can investigate the example. (Otherwise it's very difficulty to say anything at all. For example: "F" is only a character ;-))

**Comment by cube4d** [comment]
Hi,

sorry i found the problem, it was just that i dont create a NEW object every time.
Thanks
